In [24]:
import math
import numpy as np
import NeuralN

In [25]:
inputs = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
out = np.array([[0],[1],[1],[0]])


In [26]:
Model  = NeuralN.NeuralNetwork(inputs,out)

In [27]:
for i in range(1500):
    Model.feedforward()
    Model.backpropagation()
    print(Model.output)
    

[[0.62868618]
 [0.64151294]
 [0.64050131]
 [0.6522019 ]]
[[0.52165526]
 [0.5173138 ]
 [0.52251588]
 [0.51823568]]
[[0.50579518]
 [0.49892294]
 [0.50495342]
 [0.49828589]]
[[0.50520977]
 [0.49835491]
 [0.50431221]
 [0.4976525 ]]
[[0.50513401]
 [0.49837982]
 [0.50423574]
 [0.49766209]]
[[0.50507476]
 [0.49842245]
 [0.50417774]
 [0.49769127]]
[[0.50501676]
 [0.49846505]
 [0.50412133]
 [0.49772082]]
[[0.50495949]
 [0.49850706]
 [0.50406596]
 [0.49775015]]
[[0.50490293]
 [0.4985485 ]
 [0.50401163]
 [0.49777926]]
[[0.50484705]
 [0.49858936]
 [0.50395831]
 [0.49780815]]
[[0.50479181]
 [0.49862967]
 [0.50390601]
 [0.49783685]]
[[0.5047372 ]
 [0.49866943]
 [0.50385471]
 [0.49786536]]
[[0.50468318]
 [0.49870866]
 [0.50380441]
 [0.49789371]]
[[0.50462973]
 [0.49874736]
 [0.5037551 ]
 [0.49792191]]
[[0.50457683]
 [0.49878554]
 [0.50370679]
 [0.49794997]]
[[0.50452444]
 [0.49882323]
 [0.50365946]
 [0.49797791]]
[[0.50447255]
 [0.49886042]
 [0.50361311]
 [0.49800575]]
[[0.50442113]
 [0.49889713]
 [0

[[0.0224535 ]
 [0.94232851]
 [0.94279388]
 [0.06927516]]
[[0.02241727]
 [0.94243021]
 [0.94289429]
 [0.0691478 ]]
[[0.02238121]
 [0.94253149]
 [0.94299429]
 [0.06902098]]
[[0.02234533]
 [0.94263235]
 [0.94309388]
 [0.06889469]]
[[0.02230961]
 [0.94273279]
 [0.94319306]
 [0.06876893]]
[[0.02227406]
 [0.94283282]
 [0.94329183]
 [0.06864369]]
[[0.02223867]
 [0.94293244]
 [0.9433902 ]
 [0.06851898]]
[[0.02220345]
 [0.94303165]
 [0.94348817]
 [0.06839477]]
[[0.02216839]
 [0.94313046]
 [0.94358575]
 [0.06827109]]
[[0.02213349]
 [0.94322886]
 [0.94368292]
 [0.06814791]]
[[0.02209876]
 [0.94332687]
 [0.94377971]
 [0.06802524]]
[[0.02206418]
 [0.94342447]
 [0.9438761 ]
 [0.06790308]]
[[0.02202976]
 [0.94352169]
 [0.94397211]
 [0.06778141]]
[[0.0219955 ]
 [0.94361851]
 [0.94406773]
 [0.06766025]]
[[0.02196139]
 [0.94371494]
 [0.94416297]
 [0.06753958]]
[[0.02192744]
 [0.94381098]
 [0.94425783]
 [0.0674194 ]]
[[0.02189365]
 [0.94390664]
 [0.94435231]
 [0.06729971]]
[[0.02186   ]
 [0.94400192]
 [0

[[0.01377641]
 [0.96709151]
 [0.96729397]
 [0.03899751]]
[[0.01376683]
 [0.96711757]
 [0.96731979]
 [0.0389668 ]]
[[0.01375726]
 [0.96714357]
 [0.96734555]
 [0.03893615]]
[[0.01374771]
 [0.96716952]
 [0.96737127]
 [0.03890557]]
[[0.01373818]
 [0.96719542]
 [0.96739693]
 [0.03887505]]
[[0.01372866]
 [0.96722126]
 [0.96742255]
 [0.03884459]]
[[0.01371916]
 [0.96724706]
 [0.96744811]
 [0.0388142 ]]
[[0.01370968]
 [0.9672728 ]
 [0.96747362]
 [0.03878387]]
[[0.01370022]
 [0.96729849]
 [0.96749908]
 [0.0387536 ]]
[[0.01369077]
 [0.96732413]
 [0.96752449]
 [0.0387234 ]]
[[0.01368134]
 [0.96734972]
 [0.96754985]
 [0.03869325]]
[[0.01367192]
 [0.96737526]
 [0.96757516]
 [0.03866317]]
[[0.01366253]
 [0.96740075]
 [0.96760042]
 [0.03863315]]
[[0.01365315]
 [0.96742619]
 [0.96762563]
 [0.03860319]]
[[0.01364378]
 [0.96745157]
 [0.96765079]
 [0.0385733 ]]
[[0.01363444]
 [0.96747691]
 [0.9676759 ]
 [0.03854346]]
[[0.01362511]
 [0.9675022 ]
 [0.96770096]
 [0.03851369]]
[[0.01361579]
 [0.96752744]
 [0